// Custom Type for badge variants for ShadCN badge component

export const BadgeVariants = [
	"javascript",
	"typescript",
	"python",
	"ruby",
	"java",
	"go",
	"rust",
	"php",
	"csharp",
	"react",
	"vue",
	"angular",
	"svelte",
	"nextjs",
	"node",
	"tailwindcss",
	"css",
	"html",
	"graphql",
	"docker",
	"kubernetes",
	"git",
	"github",
	"vscode",
	"linux",
	"aws",
	"firebase",
	"mongodb",
	"sql",
	"webdev",
	"backend",
	"frontend",
	"opensource",
	"devops",
	"career",
	"learning",
	"productivity",
	"beginners",
	"testing",
	"design",
	"ux",
	"ai",
	"machinelearning",
	"datascience",
	"security",
	"encryption",
	"serverless",
	"cloud",
	"ci",
	"cd",
	"blockchain",
	"nft",
	"crypto",
	"webassembly",
	"pwa",
	"restapi",
	"microservices",
	"observability",
	"monitoring",
	"logging",
	"analytics",
	"bigdata",
	"elasticsearch",
	"redis",
	"postgres",
	"mysql",
	"sqlite",
	"artificialintelligence",
	"deeplearning",
	"reinforcementlearning",
	"devcommunity",
	"mentoring",
	"hackathon",
	"codingchallenge",
	"freelancing",
	"startup",
	"entrepreneurship",
	"leadership",
	"documentation",
	"api",
	"cli",
	"desktop",
	"mobile",
	"system",
	"web",
	"parse",
	"published",
	"draft",
] as const;

export type BadgeVariant = (typeof BadgeVariants)[number];

export function getSafeVariant(lang: string): BadgeVariant | "default" {
	return BadgeVariants.includes(lang as BadgeVariant)
		? (lang as BadgeVariant)
		: "default";
}
