// // Custom Type for badge variants for ShadCN badge component

// export const BadgeVariants = [
// 	"javascript",
// 	"typescript",
// 	"python",
// 	"ruby",
// 	"java",
// 	"go",
// 	"rust",
// 	"php",
// 	"csharp",
// 	"react",
// 	"vue",
// 	"angular",
// 	"svelte",
// 	"nextjs",
// 	"node",
// 	"tailwindcss",
// 	"css",
// 	"html",
// 	"graphql",
// 	"docker",
// 	"kubernetes",
// 	"git",
// 	"github",
// 	"vscode",
// 	"linux",
// 	"aws",
// 	"firebase",
// 	"mongodb",
// 	"sql",
// 	"webdev",
// 	"backend",
// 	"frontend",
// 	"opensource",
// 	"devops",
// 	"career",
// 	"learning",
// 	"productivity",
// 	"beginners",
// 	"testing",
// 	"design",
// 	"ux",
// 	"ai",
// 	"machinelearning",
// 	"datascience",
// 	"security",
// 	"encryption",
// 	"serverless",
// 	"cloud",
// 	"ci",
// 	"cd",
// 	"blockchain",
// 	"nft",
// 	"crypto",
// 	"webassembly",
// 	"pwa",
// 	"restapi",
// 	"microservices",
// 	"observability",
// 	"monitoring",
// 	"logging",
// 	"analytics",
// 	"bigdata",
// 	"elasticsearch",
// 	"redis",
// 	"postgres",
// 	"mysql",
// 	"sqlite",
// 	"artificialintelligence",
// 	"deeplearning",
// 	"reinforcementlearning",
// 	"devcommunity",
// 	"mentoring",
// 	"hackathon",
// 	"codingchallenge",
// 	"freelancing",
// 	"startup",
// 	"entrepreneurship",
// 	"leadership",
// 	"documentation",
// 	"api",
// 	"cli",
// 	"desktop",
// 	"mobile",
// 	"system",
// 	"web",
// 	"parse",
// 	"published",
// 	"draft",
// ] as const;

// export type BadgeVariant = (typeof BadgeVariants)[number];

// export function getSafeVariant(lang: string): BadgeVariant | "default" {
// 	return BadgeVariants.includes(lang as BadgeVariant)
// 		? (lang as BadgeVariant)
// 		: "default";
// }

export const tagColors: Record<string, string> = {
	javascript: "yellow",
	typescript: "blue",
	python: "green",
	ruby: "red",
	java: "orange",
	go: "cyan",
	rust: "orange",
	php: "indigo",
	csharp: "purple",
	react: "sky",
	vue: "emerald",
	angular: "red",
	svelte: "pink",
	nextjs: "gray",
	node: "green",
	tailwindcss: "teal",
	css: "blue",
	html: "orange",
	graphql: "pink",
	docker: "blue",
	kubernetes: "blue",
	git: "red",
	github: "gray",
	vscode: "indigo",
	linux: "yellow",
	aws: "orange",
	firebase: "amber",
	mongodb: "green",
	sql: "indigo",
	webdev: "purple",
	backend: "rose",
	frontend: "violet",
	opensource: "cyan",
	devops: "teal",
	career: "fuchsia",
	learning: "lime",
	productivity: "amber",
	beginners: "emerald",
	testing: "indigo",
	design: "pink",
	ux: "violet",
	ai: "purple",
	machinelearning: "green",
	datascience: "cyan",
	security: "red",
	encryption: "emerald",
	serverless: "purple",
	cloud: "blue",
	ci: "yellow",
	cd: "yellow",
	// blockchain: "indigo",
	// nft: "pink",
	// crypto: "amber",
	// webassembly: "cyan",
	// pwa: "teal",
	// restapi: "green",
	// microservices: "rose",
	// observability: "orange",
	// monitoring: "blue",
	// logging: "gray",
	// analytics: "lime",
	// bigdata: "amber",
	// elasticsearch: "orange",
	// redis: "red",
	// postgres: "blue",
	// mysql: "indigo",
	// sqlite: "violet",
	// artificialintelligence: "purple",
	// deeplearning: "fuchsia",
	// reinforcementlearning: "emerald",
	// devcommunity: "sky",
	// mentoring: "lime",
	// hackathon: "rose",
	// codingchallenge: "pink",
	// freelancing: "orange",
	// startup: "cyan",
	// entrepreneurship: "yellow",
	// leadership: "indigo",
	// documentation: "gray",
	// api: "emerald",
	// cli: "slate",
	// desktop: "stone",
	// mobile: "indigo",
	// system: "gray",
	// web: "blue",
	// parse: "purple",
	// published: "green",
	// draft: "yellow",
};

// export function getTagColorClasses(tag: string) {
// 	const color = tagColors[tag.toLowerCase()] || "gray";
// 	return `text-xl text-${color}-500 hover:bg-${color}-100`;
// }
